/* imports_direct.h -- GENERATED passthrough imports (newlib/GLESv2/EGL).
 * Symbols the game imports that map 1:1 to a devkitPro-provided function.
 * Regenerate from analysis/direct.txt. Do not edit by hand.
 */
// clang-format off
  FN(acos),
  FN(acosf),
  FN(asinf),
  FN(atan2),
  FN(atan2f),
  FN(atanf),
  FN(atof),
  FN(atoi),
  FN(atol),
  FN(atoll),
  FN(calloc),
  FN(clearerr),
  FN(closedir),
  FN(cos),
  FN(cosf),
  FN(div),
  FN(eglGetProcAddress),
  FN(exit),
  FN(exp2),
  FN(exp2f),
  FN(expf),
  { "fclose", (uintptr_t)&fclose_fake },
  FN(fdopen),
  FN(fcntl),
  { "ferror", (uintptr_t)&ferror_fake },
  { "fflush", (uintptr_t)&fflush_fake },
  FN(fileno),
  { "fgets", (uintptr_t)&fgets_fake },
  FN(fmodf),
  { "fopen", (uintptr_t)&fopen_fake },
  { "fprintf", (uintptr_t)&fprintf_fake },
  { "fputc", (uintptr_t)&fputc_fake },
  { "fputs", (uintptr_t)&fputs_fake },
  { "fread", (uintptr_t)&fread_fake },
  FN(free),
  FN(frexp),
  { "fseek", (uintptr_t)&fseek_fake },
  FN(fstat),
  { "ftell", (uintptr_t)&ftell_fake },
  { "fwrite", (uintptr_t)&fwrite_fake },
  FN(getenv),
  FN(getcwd),
  { "gettimeofday", (uintptr_t)&gettimeofday_fake },
  FN(glActiveTexture),
  FN(glAttachShader),
  FN(glBindAttribLocation),
  FN(glBindBuffer),
  { "glBindFramebuffer", (uintptr_t)&glBindFramebuffer_wrap },
  FN(glBindRenderbuffer),
  FN(glBindTexture),
  FN(glBlendEquation),
  FN(glBlendFunc),
  FN(glBufferData),
  FN(glBufferSubData),
  FN(glCheckFramebufferStatus),
  FN(glClear),
  FN(glClearColor),
  FN(glClearDepthf),
  FN(glClearStencil),
  FN(glColorMask),
  FN(glCompileShader),
  FN(glCompressedTexImage2D),
  FN(glCreateProgram),
  FN(glCreateShader),
  FN(glCullFace),
  FN(glDeleteBuffers),
  FN(glDeleteFramebuffers),
  FN(glDeleteProgram),
  FN(glDeleteRenderbuffers),
  FN(glDeleteShader),
  FN(glDeleteTextures),
  FN(glDepthFunc),
  FN(glDepthMask),
  FN(glDisable),
  FN(glDisableVertexAttribArray),
  FN(glDrawArrays),
  FN(glDrawElements),
  FN(glEnable),
  FN(glEnableVertexAttribArray),
  FN(glFramebufferRenderbuffer),
  FN(glFramebufferTexture2D),
  FN(glFrontFace),
  FN(glGenBuffers),
  FN(glGenFramebuffers),
  FN(glGenRenderbuffers),
  FN(glGenTextures),
  FN(glGenerateMipmap),
  FN(glGetActiveAttrib),
  FN(glGetActiveUniform),
  FN(glGetAttribLocation),
  FN(glGetBooleanv),
  FN(glGetError),
  FN(glGetFloatv),
  FN(glGetIntegerv),
  FN(glGetProgramInfoLog),
  FN(glGetProgramiv),
  FN(glGetShaderInfoLog),
  FN(glGetShaderSource),
  FN(glGetShaderiv),
  FN(glGetString),
  FN(glGetUniformLocation),
  FN(glHint),
  FN(glIsBuffer),
  FN(glIsEnabled),
  FN(glIsProgram),
  FN(glIsRenderbuffer),
  FN(glLineWidth),
  FN(glLinkProgram),
  FN(glPixelStorei),
  FN(glReadPixels),
  FN(glRenderbufferStorage),
  FN(glScissor),
  FN(glShaderSource),
  FN(glStencilMask),
  FN(glTexImage2D),
  FN(glTexParameterf),
  FN(glTexParameteri),
  FN(glTexSubImage2D),
  FN(glUniform1f),
  FN(glUniform1fv),
  FN(glUniform1i),
  FN(glUniform2f),
  FN(glUniform2fv),
  FN(glUniform2i),
  FN(glUniform2iv),
  FN(glUniform3f),
  FN(glUniform3fv),
  FN(glUniform3i),
  FN(glUniform3iv),
  FN(glUniform4f),
  FN(glUniform4fv),
  FN(glUniform4i),
  FN(glUniform4iv),
  FN(glUniformMatrix2fv),
  FN(glUniformMatrix3fv),
  FN(glUniformMatrix4fv),
  FN(glUseProgram),
  FN(glValidateProgram),
  FN(glVertexAttribPointer),
  { "glViewport", (uintptr_t)&glViewport_wrap },
  FN(gmtime),
  FN(isalnum),
  FN(isalpha),
  FN(isspace),
  FN(localtime),
  FN(log10),
  FN(log10f),
  FN(log2f),
  FN(logf),
  FN(longjmp),
  FN(lseek),
  FN(malloc),
  FN(mbstowcs),
  FN(memalign),
  FN(memchr),
  FN(memcmp),
  { "memcpy", (uintptr_t)&memcpy_fake },
  { "memmove", (uintptr_t)&memmove_fake },
  FN(memset),
  FN(mkdir),
  FN(modf),
  FN(mktime),
  FN(nanosleep),
  FN(opendir),
  FN(pow),
  FN(powf),
  FN(printf),
  FN(putchar),
  FN(puts),
  FN(pthread_attr_init),
  FN(pthread_attr_setschedparam),
  FN(pthread_getspecific),
  FN(pthread_join),
  FN(pthread_key_create),
  FN(pthread_self),
  FN(pthread_setspecific),
  FN(qsort),
  FN(rand),
  FN(realloc),
  FN(remove),
  FN(rename),
  { "rewind", (uintptr_t)&rewind_fake },
  FN(sched_yield),
  FN(setjmp),
  FN(setlocale),
  FN(sinf),
  FN(sin),
  FN(snprintf),
  FN(sprintf),
  FN(sqrt),
  FN(sqrtf),
  FN(srand),
  FN(sscanf),
  FN(stat),
  FN(stpcpy),
  FN(strcasecmp),
  FN(strcat),
  FN(strchr),
  FN(strcmp),
  FN(strcpy),
  FN(strdup),
  FN(strerror),
  FN(strlen),
  FN(strncat),
  FN(strncmp),
  FN(strncpy),
  FN(strpbrk),
  FN(strrchr),
  FN(strstr),
  FN(strtod),
  FN(strtok),
  FN(strtoul),
  FN(strtoull),
  FN(tan),
  FN(tanf),
  FN(time),
  FN(tolower),
  FN(toupper),
  FN(usleep),
  FN(vfprintf),
  FN(vsnprintf),
  FN(vsprintf),
  FN(wcslen),
  FN(wcstombs),
  FN(wmemcpy),
  FN(wmemmove),
  FN(wmemset),
  FN(write),
// clang-format on
